package com.senac.petshop.app;

import com.jdf.swing.helper.JFrameHelper;
import com.senac.petshop.bean.Agenda;
import com.senac.petshop.bean.Animal;
import com.senac.petshop.bean.Procedimento;
import com.senac.petshop.rn.AgendaRN;
import com.senac.petshop.swing.ManutencaoAgenda;
import com.senac.petshop.swing.ManutencaoAnimal;
import com.senac.petshop.swing.ManutencaoDono;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author lossurdo
 */
public class AppSwing extends javax.swing.JFrame {

    public AppSwing() {
        initComponents();
        
        JFrameHelper fh = new JFrameHelper(this);                 
        fh.setBiggerSize();
        
        // centraliza janela
        setLocationRelativeTo(null);               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menubar = new javax.swing.JMenuBar();
        menuAtendimento = new javax.swing.JMenu();
        menuItemAgendamento = new javax.swing.JMenuItem();
        menuItemRelatorio = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemSair = new javax.swing.JMenuItem();
        menuDono = new javax.swing.JMenu();
        menuItemManutDono = new javax.swing.JMenuItem();
        menuAnimal = new javax.swing.JMenu();
        menuItemManutAnimal = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        menuItemInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetShop4j Desktop");

        menuAtendimento.setText("Atendimento");

        menuItemAgendamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuItemAgendamento.setText("Agendamento");
        menuItemAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAgendamentoActionPerformed(evt);
            }
        });
        menuAtendimento.add(menuItemAgendamento);

        menuItemRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuItemRelatorio.setText("Relatório");
        menuItemRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelatorioActionPerformed(evt);
            }
        });
        menuAtendimento.add(menuItemRelatorio);
        menuAtendimento.add(jSeparator1);

        menuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuAtendimento.add(menuItemSair);

        menubar.add(menuAtendimento);

        menuDono.setText("Dono");

        menuItemManutDono.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuItemManutDono.setText("Manutenção");
        menuItemManutDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemManutDonoActionPerformed(evt);
            }
        });
        menuDono.add(menuItemManutDono);

        menubar.add(menuDono);

        menuAnimal.setText("Animal");

        menuItemManutAnimal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        menuItemManutAnimal.setText("Manutenção");
        menuItemManutAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemManutAnimalActionPerformed(evt);
            }
        });
        menuAnimal.add(menuItemManutAnimal);

        menubar.add(menuAnimal);

        menuSobre.setText("Sobre");

        menuItemInfo.setText("Informações...");
        menuItemInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInfoActionPerformed(evt);
            }
        });
        menuSobre.add(menuItemInfo);

        menubar.add(menuSobre);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemManutDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemManutDonoActionPerformed
                
        ManutencaoDono md = new ManutencaoDono();        
        desktopPane.add(md);
        md.setVisible(true);
        
    }//GEN-LAST:event_menuItemManutDonoActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemManutAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemManutAnimalActionPerformed
        
        ManutencaoAnimal ma = new ManutencaoAnimal();
        desktopPane.add(ma);
        ma.setVisible(true);
        
    }//GEN-LAST:event_menuItemManutAnimalActionPerformed

    private void menuItemAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAgendamentoActionPerformed
        
        ManutencaoAgenda ma = new ManutencaoAgenda();
        desktopPane.add(ma);
        ma.setVisible(true);
        
    }//GEN-LAST:event_menuItemAgendamentoActionPerformed

    private void menuItemRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatorioActionPerformed
        
        try {
            AgendaRN rn = new AgendaRN();
            List<Agenda> listaAgenda = rn.pesquisar(null);
            
            StringBuilder saidaCSV = new StringBuilder();
            // cabeçalho
            saidaCSV.append("CODIGO;DATA;ANIMAL;DONO;PROCEDIMENTO;VALOR").append("\r\n");
            
            // conteúdo do relatório
            for (Agenda la : listaAgenda) {
                for(Animal a : la.getAnimais()) {
                    for(Procedimento p : la.getProcedimentos()) {
                        saidaCSV.append(la.getCodigo()).append(";");
                        saidaCSV.append(new SimpleDateFormat("dd/MM/yyyy HH:mm").format(la.getData())).append(";");
                        saidaCSV.append(a.getNome()).append(";");                        
                        saidaCSV.append(a.getDono().getNome()).append(";");
                        saidaCSV.append(p.getNome()).append(";");
                        saidaCSV.append(p.getPreco()).append(";");
                        saidaCSV.append("\r\n");
                    }
                }
            }
            
            FileUtils.writeStringToFile(new File("relatorio.csv"), saidaCSV.toString());
            
            JOptionPane.showMessageDialog(this, "Relatório gerado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_menuItemRelatorioActionPerformed

    private void menuItemInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInfoActionPerformed
        
        JOptionPane.showMessageDialog(this, "FSPOA\r\n"
                + "Faculdade de Tecnologia Senac\r\n"
                + "Porto Alegre/RS - Brasil\r\n"
                + "Disciplina de Lab. de Programação 2\r\n"
                + "Curso de Análise e Desenvolvimento de Sistemas\r\n"
                + "Prof. Rafael Lossurdo");
        
    }//GEN-LAST:event_menuItemInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuAnimal;
    private javax.swing.JMenu menuAtendimento;
    private javax.swing.JMenu menuDono;
    private javax.swing.JMenuItem menuItemAgendamento;
    private javax.swing.JMenuItem menuItemInfo;
    private javax.swing.JMenuItem menuItemManutAnimal;
    private javax.swing.JMenuItem menuItemManutDono;
    private javax.swing.JMenuItem menuItemRelatorio;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration//GEN-END:variables
}
